### PR TITLE
Use repackaged plugins.

### PR DESCRIPTION
**Pull request by cunningt**
Use repackaged plugins from the redhat-fuse BOM.

### CODE REVIEW

**Comment by grgrzybek** [comment]
tbh, I wouldn't do it. @janstey, @chirino I think repackaging everything is bad idea. Dependencies are ok to repackage/build-from-source/productize, but maven plugins, especially because they're used as-is since .. always, should be kept with their original group:artifact

**Comment by cunningt** [comment]
@grgrzybek The benefit I see to repackaging plugins are

- we cut down on <properties/> bloat in pom.xml
- we control the version that is used, so if we make a fix in 7.3, we know it gets used in customer applications, which will cut down on support needed
- we're not repackaging everything - we are repackaging this list : https://github.com/jboss-fuse/redhat-fuse/tree/master/fuse-maven-plugins - which are the plugins that we build and a few other that deal with the packaging that is used (springboot, maven-bundle-plugin).    My preference would be to repackage as much as possible, but I don't think we can do that.

**Comment by cunningt** [comment]
@grgrzybek I think we agreed that this should go in on the call this morning, but that we should wait to process it until we get a full build of 7.3 so we can use an updated redhat-fuse - which should incorporate Freeman's fixes as well.

**Comment by cunningt** [comment]
@oscerd Can I get a review here?   These commits use the repackaged plugins, with the exception of cxf-rest/secure-cxf-rest, which is blocked by (https://issues.jboss.org/browse/ENTESB-9637).

This is being requested by QE here : https://issues.jboss.org/browse/ENTESB-9721

**Review by oscerd — APPROVED** [review]

**Pull request merged**
